DROP TABLE EMPLOYEE;
DROP TABLE TITLE;
DROP TABLE DEPARTMENT;

-- DEPARTMENT 테이블 생성
CREATE TABLE DEPARTMENT (
   DEPT_NO NUMBER(2),
   DEPT_NAME VARCHAR2(20),
   FLOOR NUMBER(2) DEFAULT 1,
   CONSTRAINT DEPARTMENT_DEPTNO_PK    PRIMARY KEY (DEPT_NO),
   CONSTRAINT DEPARTMENT_DEPTNAME_UK    UNIQUE(DEPT_NAME),
   CONSTRAINT DEPARTMENT_DEPTNAME_NN    CHECK(DEPT_NAME IS NOT NULL)
);


-- TITLE 테이블 생성
CREATE TABLE TITLE (
   TITLE_NO    NUMBER(2) CONSTRAINT TITLE_TITLENO_PK PRIMARY KEY,
   TITLE_NAME     VARCHAR2(10) CONSTRAINT TITLE_TITLENAME_NN CHECK(TITLE_NAME IS NOT NULL) CONSTRAINT TITLE_TITLENAME_UK UNIQUE
);


-- EMPLOYEE 테이블 생성
CREATE TABLE EMPLOYEE (
   EMP_NO       NUMBER,
   EMP_NAME    VARCHAR2 (20),
   TNO       NUMBER DEFAULT 1,
   MANAGER    NUMBER,
   SALARY       NUMBER,
   DNO       NUMBER DEFAULT 1);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_EMPNO_PK       PRIMARY KEY (EMP_NO);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_EMPNAME_UK    UNIQUE (EMP_NAME);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_EMPNAME_NN    CHECK(EMP_NAME IS NOT NULL);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_TNO_FK       FOREIGN KEY (TNO) REFERENCES TITLE(TITLE_NO) ON DELETE SET NULL;
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_MANAGER_FK    FOREIGN KEY (MANAGER) REFERENCES EMPLOYEE(EMP_NO);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_SALARY_CK       CHECK (SALARY < 6000000);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_DNO_CK       CHECK (DNO > 0);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_DNO_FK       FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DEPT_NO) ON DELETE CASCADE;



